Vue.component('myidea',{
	template:"#idea",
	data:function(){
		return{
			message:[],
		};
	},
	created:function(){
		this.message=[
			{
				msg:'这是一家经营已久的牛排店,我们一直以诚信为本，为顾客带来良好的味的体验，带来家的味道，而且实惠又美味'
			},
			{
				msg:'这是一家经营已久的湘菜馆，我们一直以诚信为本，为顾客带来良好的味的体验，带来家的味道，而且实惠又美味'
			},
			{
				msg:'这是一家经营已久的粥店，我们一直以诚信为本，为顾客带来良好的味的体验，带来家的味道，而且实惠又美味'
			},
			{
				msg:'这是一家经营已久的甜点店，我们一直以诚信为本，为顾客带来良好的味的体验，带来家的味道，而且实惠又美味'
			}
		]
	},
	methods:{
		changeMsg:function(){

		}
	}
});