//商家信息
//12345分别是爵士牛排，水煮江川，粥末，湘菜，思维特

seller-data

db.seller.find():
[
	{
		seller_id:'01',
		seller_pic:'images/seller/seller_1.png',  //商家头像
		seller_name:'爵士牛排', //商家名称
		seller_intro:'只有你想不到，没有我们做不到，美味尽在爵士牛排', //商家简介
		seller_acti:'全场满99减5', //商家活动（全场几折）
		seller_notice:'开张大吉，生意兴隆',      //商家公告
		start_price:'¥45', //起步价
		delivery_fee:'¥3',  //配送费
		delivery_time:'30分钟即达', //配送时间（周几到周几，几点到几点）
		seller_sales:'月售492单', //月销售量
		seller_tel:'18701235566',  //商家联系方式
		seller_address:'华旭曼度广场2F', //商家地址
		seller_foods:[  //菜品
			{	
				food_id:'01-001',
				seller_id:'01',
				seller_name:'爵士牛排', //商家名称
				food_name:'菲力牛排', //名字
				food_old_price:'￥239',  //原价
				food_price:'￥199', //价格
				food_sales:'56单',  //月销售量
				food_pic:'images/foods/foods_1/00-01.jpg',   //菜图
				food_intro:'西方人眼中的"眼菲力"，厚度相当的牛里脊肉，味道鲜美'  //菜简介
 			},    
			{
				food_id:'01-002',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'沙拉排',
				food_old_price:'￥158',
				food_price:'￥139',
				food_sales:'48单',
				food_pic:'images/foods/foods_1/00-02.jpg',
				food_intro:'各种蔬菜水果组合而成，健康营养又美味，适合各种年龄的顾客上帝们'
			},
			{
				food_id:'01-003',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'西冷牛排',
				food_old_price:'￥268',
				food_price:'￥219',
				food_sales:'89单',
				food_pic:'images/foods/foods_1/00-03.jpg',
				food_intro:'沙朗牛排，是外脊肉，牛的后腰肉，含一定肥油，尤其是外延有一圈呈白色的肉筋，上口相比菲力牛排更有韧性、有嚼劲，适合年轻人和牙口好的人'
			},
			{
				food_id:'01-004',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'拿铁',
				food_old_price:'￥99',
				food_price:'￥68',
				food_sales:'167单',
				food_pic:'images/foods/foods_1/00-04.jpg',
				food_intro:'热气腾腾他的拿铁，让你我之间更有爱，其中含有丰富的牛奶，让奶香给亲们带来难以忘怀的味道'
			},
			{
				food_id:'01-005',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'水果世界',
				food_old_price:'￥58',
				food_price:'￥49',
				food_sales:'176单',
				food_pic:'images/foods/foods_1/00-05.jpg',
				food_intro:'牛排过后，带上帝们来到来到水果的世界，各种新鲜水果，现榨成汁儿，浓浓的果香让您忘却烦恼'
			},
			{
				food_id:'01-006',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'香炸鲜虾',
				food_old_price:'￥88',
				food_price:'￥78',
				food_sales:'57单',
				food_pic:'images/foods/foods_1/00-06.jpg',
				food_intro:'深海中的虾，绝对的干净，肥美鲜香'
			},
			{
				food_id:'01-007',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'T骨牛排',
				food_old_price:'￥179',
				food_price:'￥168',
				food_sales:'单',
				food_pic:'images/foods/foods_1/00-06.jpg',
				food_intro:'牛背上的脊骨肉，呈T字型，两侧一边是菲力，另一边是西冷，既可以尝到菲力牛排的鲜嫩又可以感受到西冷牛排的芳香，一举两得'
			},
			{
				food_id:'01-008',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'肉眼牛排',
				food_old_price:'￥248',
				food_price:'￥234',
				food_sales:'单',
				food_pic:'images/foods/foods_1/00-08.jpg',
				food_intro:'牛肋上的肉，瘦肉和肥肉兼而有之，由于含一定肥膘，这种肉煎烤味道比较香'
			},
			{
				food_id:'01-009',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'牛排早餐',
				food_old_price:'￥134',
				food_price:'￥124',
				food_sales:'122单',
				food_pic:'images/foods/foods_1/00-09.jpg',
				food_intro:'营养丰富，美味可口'
			},
			{
				food_id:'01-010',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'风味排',
				food_old_price:'￥99',
				food_price:'￥78',
				food_sales:'156单',
				food_pic:'images/foods/foods_1/00-10.jpg',
				food_intro:'美味油炸，新鲜蔬菜，配上可口牛排'
			},
			{
				food_id:'01-011',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'豆柿牛排',
				food_old_price:'￥67',
				food_price:'￥65',
				food_sales:'单',
				food_pic:'images/foods/foods_1/00-11.jpg',
				food_intro:'平凡中的美味与高贵'
			},
			{
				food_id:'01-012',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'柿绛双排',
				food_old_price:'￥189',
				food_price:'￥179',
				food_sales:'34单',
				food_pic:'images/foods/foods_1/00-12.jpg',
				food_intro:'双份牛排，实惠可口，配上新鲜果汁'
			},
			{
				food_id:'01-013',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'红酒牛排',
				food_old_price:'￥78',
				food_price:'￥75',
				food_sales:'178单',
				food_pic:'images/foods/foods_1/00-13.jpg',
				food_intro:'红酒浸制而成，好吃'
			},
			{
				food_id:'01-014',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'爱心牛排',
				food_old_price:'￥89',
				food_price:'￥88',
				food_sales:'单',
				food_pic:'images/foods/foods_1/00-14.jpg',
				food_intro:'有爱才有美味，和你的她共享吧'
			},
			{
				food_id:'01-015',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'柿红肥排',
				food_old_price:'￥67',
				food_price:'￥56',
				food_sales:'56单',
				food_pic:'images/foods/foods_1/00-15.jpg',
				food_intro:'聚实惠，巨实惠'
			},
			{
				food_id:'01-016',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'酱牛排',
				food_old_price:'￥105',
				food_price:'￥99',
				food_sales:'78单',
				food_pic:'images/foods/foods_1/00-16.jpg',
				food_intro:'秘制酱料，让你吃的流连忘返'
			},
			{
				food_id:'01-017',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'果排',
				food_old_price:'￥56',
				food_price:'￥54',
				food_sales:'45单',
				food_pic:'images/foods/foods_1/00-17.jpg',
				food_intro:'牛排配水果，营养实惠'
			},
			{
				food_id:'01-018',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'绿丝排骨',
				food_old_price:'￥108',
				food_price:'￥106',
				food_sales:'46单',
				food_pic:'images/foods/foods_1/00-18.jpg',
				food_intro:'新鲜绿色蔬菜丝加上酱排骨，好看又好吃'
			},
			{
				food_id:'01-019',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'果酱黄排',
				food_old_price:'￥78',
				food_price:'￥67',
				food_sales:'133单',
				food_pic:'images/foods/foods_1/00-19.jpg',
				food_intro:'舌尖上的南瓜酱汁排'
			},
			{
				food_id:'01-020',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'牛排套餐',
				food_old_price:'￥89',
				food_price:'￥87',
				food_sales:'57单',
				food_pic:'images/foods/foods_1/00-20.jpg',
				food_intro:'物美价廉，还好吃'
			},
			{
				food_id:'01-021',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'简排',
				food_old_price:'￥76',
				food_price:'￥69',
				food_sales:'145单',
				food_pic:'images/foods/foods_1/00-21.jpg',
				food_intro:'看起来平凡，吃起来却不平凡'
			},
			{
				food_id:'01-022',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'牛排蔬果汇',
				food_old_price:'￥189',
				food_price:'￥176',
				food_sales:'366单',
				food_pic:'images/foods/foods_1/00-22.jpg',
				food_intro:'营养丰富，好吃'
			},
			{
				food_id:'01-023',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'黄玉牛排',
				food_old_price:'￥56',
				food_price:'￥54',
				food_sales:'32单',
				food_pic:'images/foods/foods_1/00-23.jpg',
				food_intro:'蛋白质超级丰富，补充能量的好帮手'
			},
			{
				food_id:'01-024',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'四面八方',
				food_old_price:'￥59',
				food_price:'￥55',
				food_sales:'194单',
				food_pic:'images/foods/foods_1/00-24.jpg',
				food_intro:'外形简单，美味'
			},
			{
				food_id:'01-025',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'洪豆酱排',
				food_old_price:'￥245',
				food_price:'￥239',
				food_sales:'56单',
				food_pic:'images/foods/foods_1/00-25.jpg',
				food_intro:'超薄的美味，红豆入口即化'
			},
			{
				food_id:'01-026',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'黄绿排',
				food_old_price:'￥54',
				food_price:'￥49',
				food_sales:'175单',
				food_pic:'images/foods/foods_1/00-26.jpg',
				food_intro:'营养健康，美味早餐'
			},
			{
				food_id:'01-027',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'格调牛排',
				food_old_price:'￥324',
				food_price:'￥299',
				food_sales:'167单',
				food_pic:'images/foods/foods_1/00-27.jpg',
				food_intro:'贵族般的享受'
			},
			{
				food_id:'01-028',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'果排套餐',
				food_old_price:'￥314',
				food_price:'￥289',
				food_sales:'35单',
				food_pic:'images/foods/foods_1/00-28.jpg',
				food_intro:'超值套餐，多人共享'
			},
			{
				food_id:'01-029',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'薯条牛排',
				food_old_price:'￥65',
				food_price:'￥59',
				food_sales:'156单',
				food_pic:'images/foods/foods_1/00-29.jpg',
				food_intro:'牛排和炸薯条很配'
			},
			{
				food_id:'01-030',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'玉米骨排',
				food_old_price:'￥54',
				food_price:'￥48',
				food_sales:'29单',
				food_pic:'images/foods/foods_1/00-30.jpg',
				food_intro:'人人都消费得起的超值牛排'
			},
			{
				food_id:'01-031',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'粉色浪漫',
				food_old_price:'￥189',
				food_price:'￥179',
				food_sales:'67单',
				food_pic:'images/foods/foods_1/00-31.jpg',
				food_intro:'粉色般的浪漫，向你的她表白吧'
			},
			{
				food_id:'01-032',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'意大利排',
				food_old_price:'￥165',
				food_price:'￥156',
				food_sales:'30单',
				food_pic:'images/foods/foods_1/00-32.jpg',
				food_intro:'既可以吃牛排又可以吃意大利面'
			},
			{
				food_id:'01-033',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'鸡蛋排',
				food_old_price:'￥54',
				food_price:'￥48',
				food_sales:'98单',
				food_pic:'images/foods/foods_1/00-33.jpg',
				food_intro:'滋补的好方法'
			},

			{
				food_id:'01-034',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'蔬果面包',
				food_old_price:'￥58',
				food_price:'￥55',
				food_sales:'321单',
				food_pic:'images/foods/foods_1/00-34.jpg',
				food_intro:'新鲜的蔬菜水果和面包，早餐的好选择'
			},
			{
				food_id:'01-035',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'温馨',
				food_old_price:'￥245',
				food_price:'￥239',
				food_sales:'75单',
				food_pic:'images/foods/foods_1/00-35.jpg',
				food_intro:'尽享温馨时刻'
			},
			{
				food_id:'01-036',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'藕断丝连',
				food_old_price:'￥176',
				food_price:'￥160',
				food_sales:'45单',
				food_pic:'images/foods/foods_1/00-36.jpg',
				food_intro:'美味可口，好吃好吃'
			},
			{
				food_id:'01-037',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'酱排',
				food_old_price:'￥45',
				food_price:'￥39',
				food_sales:'327单',
				food_pic:'images/foods/foods_1/00-37.jpg',
				food_intro:'活泼中的美味，你值得拥有'
			},
			{
				food_id:'01-038',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'牛排大餐',
				food_old_price:'￥587',
				food_price:'￥569',
				food_sales:'18单',
				food_pic:'images/foods/foods_1/00-38.jpg',
				food_intro:'可以喝小伙伴们一起共享哦'
			},
			{
				food_id:'01-039',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'菇星牛排',
				food_old_price:'￥145',
				food_price:'￥139',
				food_sales:'96单',
				food_pic:'images/foods/foods_1/00-39.jpg',
				food_intro:'营养不失美味的牛排哦'
			},
			{
				food_id:'01-040',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'柠檬牛排',
				food_old_price:'￥76',
				food_price:'￥69',
				food_sales:'145单',
				food_pic:'images/foods/foods_1/00-40.jpg',
				food_intro:'清新美味又可口'
			},
			{
				food_id:'01-041',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'三三圆排',
				food_old_price:'￥76',
				food_price:'￥69',
				food_sales:'单167',
				food_pic:'images/foods/foods_1/00-41.jpg',
				food_intro:'三种口味，好吃得不得了'
			},
			{
				food_id:'01-042',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'西黄牛排',
				food_old_price:'￥69',
				food_price:'￥58',
				food_sales:'261单',
				food_pic:'images/foods/foods_1/00-42.jpg',
				food_intro:'实惠好吃分量多'
			},
			{
				food_id:'01-043',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'里脊排',
				food_old_price:'￥86',
				food_price:'￥79',
				food_sales:'167单',
				food_pic:'images/foods/foods_1/00-43.jpg',
				food_intro:'秘制酱汁和里脊肉搭配'
			},
			{
				food_id:'01-044',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'心心相印',
				food_old_price:'￥236',
				food_price:'￥219',
				food_sales:'67单',
				food_pic:'images/foods/foods_1/00-44.jpg',
				food_intro:'外形是心，吃起来很好吃，有爱'
			},
			{
				food_id:'01-045',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'思思丝丝',
				food_old_price:'￥89',
				food_price:'￥76',
				food_sales:'85单',
				food_pic:'images/foods/foods_1/00-45.jpg',
				food_intro:'吃起来肉也是一丝一丝的，丝滑爽口'
			},
			{
				food_id:'01-046',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'炭烤牛排',
				food_old_price:'￥99',
				food_price:'￥85',
				food_sales:'76单',
				food_pic:'images/foods/foods_1/00-46.jpg',
				food_intro:'火焰山的牛排更显活力，更有嚼劲'
			},
			{
				food_id:'01-047',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'骨肉相连',
				food_old_price:'￥167',
				food_price:'￥135',
				food_sales:'56单',
				food_pic:'images/foods/foods_1/00-47.jpg',
				food_intro:'美味爽口味道一绝'
			},
			{
				food_id:'01-048',
				seller_id:'01',
				seller_name:'爵士牛排',
				food_name:'青红椒排',
				food_old_price:'￥99',
				food_price:'￥89',
				food_sales:'267单',
				food_pic:'images/foods/foods_1/00-48.jpg',
				food_intro:'可口的牛排加上微微的辣感'
			}
		]
	},
	{
		seller_id:'02',
		seller_pic:'images/seller/seller_2.png',  //商家头像
		seller_name:'水煮江川', //商家名称
		seller_intro:'骨汤水煮领导者,一锅一汤,美味健康', //商家简介
		seller_acti:'首次下单赠饮料一瓶，送完即止', //商家活动（全场几折）
		seller_notice:'专注数十年,正宗,高端,极具品质的水煮江川,成就全国知名品牌',  //商家公告
		start_price:'¥10', //起步价
		delivery_fee:'¥3',  //配送费
		delivery_time:'40分钟即达', //配送时间
		seller_sales:'月售2678单', //月销售量
		seller_tel: '18279190132',
		seller_address:'志敏大道江西农业大学商业街麻辣烫201号', //商家地址
		seller_foods:[  //菜品
			{
				food_id:'02-001',
				seller_id:'02',
				seller_name:'水煮江川', //商家名称
				food_name:'爆炒牛肉', //名字
				food_old_price:'¥200',
				food_price:'¥45', //价格
				food_sales:'456单',  //月销售量
				food_pic:'images/foods/foods_2/00-01.jpg',   //菜图
				food_intro:'牛肉软嫩，补中益气菜肴'  //菜简介
 			},    
			{
				food_id:'02-002',
				seller_id:'02',
				seller_name:'水煮江川', //商家名称
				food_name:'辣椒爆肠', //名字
				food_old_price:'¥200',
				food_price:'¥33', //价格
				food_sales:'23单',  //月销售量
				food_pic:'images/foods/foods_2/00-02.jpg',   //菜图
				food_intro:'美味可口的汉族名菜'  //菜简介
 			}, 
			{
				food_id:'02-003',
				seller_id:'02',
				seller_name:'水煮江川', //商家名称
				food_name:'糖醋排骨', //名字
				food_old_price:'¥200',
				food_price:'¥56', //价格
				food_sales:'567单',  //月销售量
				food_pic:'images/foods/foods_2/00-03.jpg',   //菜图
				food_intro:'舌尖上的家常美食'  //菜简介
 			}, 
			{
				food_id:'02-004',
				seller_id:'02',
				seller_name:'水煮江川', //商家名称
				food_name:'焖鸡', //名字
				food_old_price:'¥200',
				food_price:'¥76', //价格
				food_sales:'42单',  //月销售量
				food_pic:'images/foods/foods_2/00-04.jpg',   //菜图
				food_intro:'营养又不失美味的佳肴'  //菜简介
 			}, 
			{
				food_id:'02-005',
				seller_id:'02',
				seller_name:'水煮江川', //商家名称
				food_name:'麻辣火锅', //名字
				food_old_price:'¥200',
				food_price:'¥34', //价格
				food_sales:'100单',  //月销售量
				food_pic:'images/foods/foods_2/00-05.jpg',   //菜图
				food_intro:'麻辣鲜香，利水消肿'  //菜简介
 			}, 
			{
				food_id:'02-006',
				seller_id:'02',
				seller_name:'水煮江川', //商家名称
				food_name:'清蒸鱼棒', //名字
				food_old_price:'¥200',
				food_price:'¥22', //价格
				food_sales:'324单',  //月销售量
				food_pic:'images/foods/foods_2/00-06.jpg',   //菜图
				food_intro:'一道常见的家常菜'  //菜简介
 			}, 
			{
				food_id:'02-007',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'麻婆豆腐',
				food_old_price:'¥200',
				food_price:'¥22',
				food_sales:'789单',
				food_pic:'images/foods/foods_2/00-07.jpg',
				food_intro:'香辣可口的家庭美食'
 			}, 
 			{
				food_id:'02-008',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮粉丝',
				food_old_price:'¥200',
				food_price:'¥38',
				food_sales:'342单',
				food_pic:'images/foods/foods_2/00-08.jpg',
				food_intro:'香辣可口，绝对美味'
 			}, 
 			{
				food_id:'02-009',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'干锅粉丝',
				food_old_price:'¥200',
				food_price:'¥36',
				food_sales:'325单',
				food_pic:'images/foods/foods_2/00-09.jpg',
				food_intro:'好吃好吃，超级好吃'
 			}, 
 			{
				food_id:'02-010',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'麻辣鸭',
				food_old_price:'¥200',
				food_price:'¥87',
				food_sales:'167单',
				food_pic:'images/foods/foods_2/00-10.jpg',
				food_intro:'绝对正宗的鸭，超级美味'
 			}, 
 			{
				food_id:'02-011',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'西兰花肉丁',
				food_old_price:'¥200',
				food_price:'¥98',
				food_sales:'267单',
				food_pic:'images/foods/foods_2/00-11.jpg',
				food_intro:'蔬菜和肉，均衡营养'
 			}, 
 			{
				food_id:'02-012',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'茶树菇焖鸡',
				food_old_price:'¥200',
				food_price:'¥108',
				food_sales:'94单',
				food_pic:'images/foods/foods_2/00-12.jpg',
				food_intro:'茶树菇焖的鸡，味美汤营养'
 			}, 
 			{
				food_id:'02-013',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'土豆焖肉丁',
				food_old_price:'¥200',
				food_price:'¥89',
				food_sales:'157单',
				food_pic:'images/foods/foods_2/00-13.jpg',
				food_intro:'好吃可口的家常菜'
 			}, 
 			{
				food_id:'02-014',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'海鲜大餐',
				food_old_price:'¥200',
				food_price:'¥178',
				food_sales:'256单',
				food_pic:'images/foods/foods_2/00-14.jpg',
				food_intro:'超级好吃的海鲜汇'
 			}, 
 			{
				food_id:'02-015',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'闻鸡起舞',
				food_old_price:'¥200',
				food_price:'¥145',
				food_sales:'93单',
				food_pic:'images/foods/foods_2/00-15.jpg',
				food_intro:'色香味俱全阿吉吗都喜欢吃的鸡'
 			}, 
 			{
				food_id:'02-016',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'叫花鸡',
				food_old_price:'¥200',
				food_price:'¥156',
				food_sales:'234单',
				food_pic:'images/foods/foods_2/00-16.jpg',
				food_intro:'超级好吃传统方法做成的烤鸡'
 			}, 
 			{
				food_id:'02-017',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'爆炒虾仁',
				food_old_price:'¥200',
				food_price:'¥98',
				food_sales:'145单',
				food_pic:'images/foods/foods_2/00-17.jpg',
				food_intro:'美味中的美味，海鲜者的喜爱'
 			}, 
 			{
				food_id:'02-018',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'果蹄',
				food_old_price:'¥200',
				food_price:'¥98',
				food_sales:'453单',
				food_pic:'images/foods/foods_2/00-18.jpg',
				food_intro:'不但好吃，还含有丰富的胶原蛋白'
 			}, 
 			{
				food_id:'02-019',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'麻辣鱼',
				food_old_price:'¥200',
				food_price:'¥88',
				food_sales:'324单',
				food_pic:'images/foods/foods_2/00-19.jpg',
				food_intro:'好好吃的麻辣鱼'
 			}, 
 			{
				food_id:'02-020',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'玉米排骨汤',
				food_old_price:'¥200',
				food_price:'¥48',
				food_sales:'234单',
				food_pic:'images/foods/foods_2/00-20.jpg',
				food_intro:'营养丰富，汤的最佳选择'
 			}, 
 			{
				food_id:'02-021',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'剁椒鱼头',
				food_old_price:'¥200',
				food_price:'¥87',
				food_sales:'544单',
				food_pic:'images/foods/foods_2/00-21.jpg',
				food_intro:'辣辣辣，绝对美味'
 			}, 
 			{
				food_id:'02-022',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'肉排拱桥',
				food_old_price:'¥200',
				food_price:'¥108',
				food_sales:'343单',
				food_pic:'images/foods/foods_2/00-22.jpg',
				food_intro:'设计独特，营养丰富，好吃，辣味十足'
 			}, 
 			{
				food_id:'02-023',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'汤圆',
				food_old_price:'¥200',
				food_price:'¥18',
				food_sales:'332单',
				food_pic:'images/foods/foods_2/00-23.jpg',
				food_intro:'营养丰富的早晚餐'
 			}, 
 			{
				food_id:'02-024',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'红烧肉片',
				food_old_price:'¥200',
				food_price:'¥58',
				food_sales:'456单',
				food_pic:'images/foods/foods_2/00-24.jpg',
				food_intro:'绝对的瘦肉，不惨任何肥肉，吃起来超级有味道'
 			}, 
 			{
				food_id:'02-025',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮鸭',
				food_old_price:'¥200',
				food_price:'¥78',
				food_sales:'145单',
				food_pic:'images/foods/foods_2/00-25.jpg',
				food_intro:'很营养的鸭汤，鸭也很爽口'
 			}, 
 			{
				food_id:'02-026',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'土豆烧肉',
				food_old_price:'¥200',
				food_price:'¥35',
				food_sales:'534单',
				food_pic:'images/foods/foods_2/00-26.jpg',
				food_intro:'人人都消费得起的好吃的家常菜'
 			}, 
 			{
				food_id:'02-027',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'天女散花',
				food_old_price:'¥200',
				food_price:'¥128',
				food_sales:'154单',
				food_pic:'images/foods/foods_2/00-27.jpg',
				food_intro:'看起来好看，吃起来简直美味'
 			}, 
 			{
				food_id:'02-028',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'披萨',
				food_old_price:'¥200',
				food_price:'¥57',
				food_sales:'456单',
				food_pic:'images/foods/foods_2/00-28.jpg',
				food_intro:'好吃有嚼劲'
 			}, 
 			{
				food_id:'02-029',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'炒肉片',
				food_old_price:'¥200',
				food_price:'¥35',
				food_sales:'353单',
				food_pic:'images/foods/foods_2/00-29.jpg',
				food_intro:'唇齿留香，色味俱佳'
 			}, 
 			{
				food_id:'02-030',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'鸳鸯锅',
				food_old_price:'¥200',
				food_price:'¥98',
				food_sales:'321单',
				food_pic:'images/foods/foods_2/00-30.jpg',
				food_intro:'口舌生香大快朵颐'
 			}, 
 			{
				food_id:'02-031',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'人间方圆',
				food_old_price:'¥200',
				food_price:'¥78',
				food_sales:'34单',
				food_pic:'images/foods/foods_2/00-31.jpg',
				food_intro:'外观温馨，看起来有食欲，吃着更有味'
 			}, 
 			{
				food_id:'02-032',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'猪蹄面',
				food_old_price:'¥200',
				food_price:'¥28',
				food_sales:'532单',
				food_pic:'images/foods/foods_2/00-32.jpg',
				food_intro:'营养丰富，美容养颜'
 			}, 
 			{
				food_id:'02-033',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'干锅鱿鱼丝',
				food_old_price:'¥200',
				food_price:'¥56',
				food_sales:'643单',
				food_pic:'images/foods/foods_2/00-33.jpg',
				food_intro:'鱿鱼，营养丰富，好吃好吃'
 			}, 
 			{
				food_id:'02-034',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮酱干',
				food_old_price:'¥200',
				food_price:'¥34',
				food_sales:'456单',
				food_pic:'images/foods/foods_2/00-34.jpg',
				food_intro:'既好吃又实惠'
 			}, 
 			{
				food_id:'02-035',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮豆皮',
				food_old_price:'¥200',
				food_price:'¥28',
				food_sales:'245单',
				food_pic:'images/foods/foods_2/00-35.jpg',
				food_intro:'平凡中的美味，美味'
 			},
 			{
				food_id:'02-036',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮肉片',
				food_old_price:'¥200',
				food_price:'¥65',
				food_sales:'324单',
				food_pic:'images/foods/foods_2/00-36.jpg',
				food_intro:'巨好吃，还营养'
 			}, 
 			{
				food_id:'02-037',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'皮蛋苋菜',
				food_old_price:'¥200',
				food_price:'¥35',
				food_sales:'268单',
				food_pic:'images/foods/foods_2/00-37.jpg',
				food_intro:'营养丰富的家常菜'
 			}, 
 			{
				food_id:'02-038',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'豆皮火腿丝',
				food_old_price:'¥200',
				food_price:'¥25',
				food_sales:'324单',
				food_pic:'images/foods/foods_2/00-38.jpg',
				food_intro:'小孩子喜欢吃的美味'
 			}, 
 			{
				food_id:'02-039',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮鸭舌',
				food_old_price:'¥200',
				food_price:'¥88',
				food_sales:'76单',
				food_pic:'images/foods/foods_2/00-39.jpg',
				food_intro:'营养不失美味，辣味十足'
 			}, 
 			{
				food_id:'02-040',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮扣肉',
				food_old_price:'¥200',
				food_price:'¥109',
				food_sales:'89单',
				food_pic:'images/foods/foods_2/00-40.jpg',
				food_intro:'口感好，扣肉入口即化'
 			}, 
 			{
				food_id:'02-041',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮三鲜',
				food_old_price:'¥200',
				food_price:'¥145',
				food_sales:'139单',
				food_pic:'images/foods/foods_2/00-41.jpg',
				food_intro:'海鲜水煮，味美爽口'
 			}, 
 			{
				food_id:'02-042',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮牛肉',
				food_old_price:'¥200',
				food_price:'¥87',
				food_sales:'345单',
				food_pic:'images/foods/foods_2/00-42.jpg',
				food_intro:'很有口感的牛肉，好吃又可以补充能量'
 			}, 
 			{
				food_id:'02-043',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮猪血',
				food_old_price:'¥200',
				food_price:'¥65',
				food_sales:'124单',
				food_pic:'images/foods/foods_2/00-43.jpg',
				food_intro:'生姜去腥，色香味俱全'
 			}, 
 			{
				food_id:'02-044',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮泥鳅',
				food_old_price:'¥200',
				food_price:'¥128',
				food_sales:'87单',
				food_pic:'images/foods/foods_2/00-44.jpg',
				food_intro:'好吃好吃，超级好吃'
 			}, 
 			{
				food_id:'02-045',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮茶树菇',
				food_old_price:'¥200',
				food_price:'¥60',
				food_sales:'456单',
				food_pic:'images/foods/foods_2/00-45.jpg',
				food_intro:'营养丰富，美味可口'
 			}, 
 			{
				food_id:'02-046',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮鱼',
				food_old_price:'¥200',
				food_price:'¥56',
				food_sales:'478单',
				food_pic:'images/foods/foods_2/00-46.jpg',
				food_intro:'鱼鲜味美，丝滑爽口'
 			}, 
 			{
				food_id:'02-047',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮青菜',
				food_old_price:'¥200',
				food_price:'¥28',
				food_sales:'324单',
				food_pic:'images/foods/foods_2/00-47.jpg',
				food_intro:'健康营养，平凡中的美味'
 			}, 
 			{
				food_id:'02-048',
				seller_id:'02',
				seller_name:'水煮江川',
				food_name:'水煮排骨',
				food_old_price:'¥200',
				food_price:'¥68',
				food_sales:'123单',
				food_pic:'images/foods/foods_2/00-48.jpg',
				food_intro:'排骨，不再是清煮，而是水煮，带有辣味的排骨'
 			}
		]
	},
	{
		seller_id:'03',
		seller_pic:'images/seller/seller_3.png',  //商家头像
		seller_name:'粥末', //商家名称
		seller_intro:'针对体质研发养生粥，五谷食材，老少皆宜，百搭美味平民价', //商家简介
		seller_acti:'全场八折', //商家活动（全场几折）
		seller_notice:'薏米红豆汤,鲜虾粥,百合薏仁粥,杂蔬瘦肉粥,皮蛋香粥,鸡肉蔬菜粥,皮蛋瘦肉粥,皮蛋瘦肉粥...你想要的我们都有',      //商家公告
		start_price:'¥8', //起步价
		delivery_fee:'¥4',  //配送费
		delivery_time:'50分钟即达', //配送时间
		seller_sales:'月售3454单', //月销售量
		seller_tel: '18279190132',
		seller_address:'志敏大道江西农业大学商业街粥末111号', //商家地址
		seller_foods:[  //菜品
			{
				food_id:'03-001',
				seller_id:'03',
				seller_name:'粥末', //商家名称
				food_name:'萝卜瘦肉粥', //名字
				food_old_price:'¥300',
				food_price:'¥22', //价格
				food_sales:'324单',  //月销售量
				food_pic:'images/foods/foods_3/00-01.jpg',   //菜图
				food_intro:'营养健康老少皆宜'  //菜简介
 			},   
			{
				food_id:'03-002',
				seller_id:'03',
				seller_name:'粥末', //商家名称
				food_name:'红豆玉米胡萝卜粥', //名字
				food_old_price:'¥300',
				food_price:'¥22', //价格
				food_sales:'324单',  //月销售量
				food_pic:'images/foods/foods_3/00-02.jpg',   //菜图
				food_intro:'清淡去火，营养佳品'  //菜简介
 			},
			{
				food_id:'03-003',
				seller_id:'03',
				seller_name:'粥末', //商家名称
				food_name:'海带肉丝粥', //名字
				food_old_price:'¥300',
				food_price:'¥10', //价格
				food_sales:'34单',  //月销售量
				food_pic:'images/foods/foods_3/00-03.jpg',   //菜图
				food_intro:'一道营养又不失美味的养生粥'  //菜简介
 			},
			{
				food_id:'03-004',
				seller_id:'03',
				seller_name:'粥末', //商家名称
				food_name:'蘑菇瘦肉粥', //名字
				food_old_price:'¥300',
				food_price:'¥33', //价格
				food_sales:'364单',  //月销售量
				food_pic:'images/foods/foods_3/00-04.jpg',   //菜图
				food_intro:'一道常见的家常菜'  //菜简介
 			},
			{
				food_id:'03-005',
				seller_id:'03',
				seller_name:'粥末', //商家名称
				food_name:'胡萝卜清粥', //名字
				food_old_price:'¥300',
				food_price:'¥21', //价格
				food_sales:'67单',  //月销售量
				food_pic:'images/foods/foods_3/00-05.jpg',   //菜图
				food_intro:'香软美味小米制成美食'  //菜简介
 			},
			{
				food_id:'03-006',
				seller_id:'03',
				seller_name:'粥末', //商家名称
				food_name:'洋葱红枣粥', //名字
				food_old_price:'¥300',
				food_price:'¥15', //价格
				food_sales:'90单',  //月销售量
				food_pic:'images/foods/foods_3/00-06.jpg',   //菜图
				food_intro:'具降火消暑之功效'  //菜简介
 			},
			{
				food_id:'03-007',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'皮蛋瘦肉粥',
				food_old_price:'¥300',
				food_price:'¥16',
				food_sales:'25单',
				food_pic:'images/foods/foods_3/00-07.jpg',
				food_intro:'一定是你吃过最好的皮蛋'
 			},
 			{
				food_id:'03-008',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'红枣小米粥',
				food_old_price:'¥300',
				food_price:'¥25',
				food_sales:'45单',
				food_pic:'images/foods/foods_3/00-08.jpg',
				food_intro:'好看又好吃'
 			},
 			{
				food_id:'03-009',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'青菜皮蛋粥',
				food_old_price:'¥300',
				food_price:'¥18',
				food_sales:'76单',
				food_pic:'images/foods/foods_3/00-09.jpg',
				food_intro:'营养丰富，早餐的选择'
 			},
 			{
				food_id:'03-010',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'排骨粥',
				food_old_price:'¥300',
				food_price:'¥35',
				food_sales:'87单',
				food_pic:'images/foods/foods_3/00-10.jpg',
				food_intro:'好吃营养，排骨细腻'
 			},
 			{
				food_id:'03-011',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'草莓粥',
				food_old_price:'¥300',
				food_price:'¥28',
				food_sales:'324单',
				food_pic:'images/foods/foods_3/00-11.jpg',
				food_intro:'好吃的水果粥，小孩子们的最爱哦'
 			},
 			{
				food_id:'03-012',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'南瓜粥',
				food_old_price:'¥300',
				food_price:'¥25',
				food_sales:'322单',
				food_pic:'images/foods/foods_3/00-12.jpg',
				food_intro:'老少皆宜，营养健康'
 			},
 			{
				food_id:'03-013',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'蓝莓枸杞粥',
				food_old_price:'¥300',
				food_price:'¥38',
				food_sales:'122单',
				food_pic:'images/foods/foods_3/00-13.jpg',
				food_intro:'营养丰富，对眼睛有好处'
 			},
 			{
				food_id:'03-014',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'鸡蛋瘦肉粥',
				food_old_price:'¥300',
				food_price:'¥27',
				food_sales:'232单',
				food_pic:'images/foods/foods_3/00-14.jpg',
				food_intro:'含有丰富的蛋白质，还很美味'
 			},
 			{
				food_id:'03-015',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'香菇青菜粥',
				food_old_price:'¥300',
				food_price:'¥18',
				food_sales:'233单',
				food_pic:'images/foods/foods_3/00-15.jpg',
				food_intro:'香甜美味，营养丰富'
 			},
 			{
				food_id:'03-016',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'皮蛋红枣粥',
				food_old_price:'¥300',
				food_price:'¥24',
				food_sales:'46单',
				food_pic:'images/foods/foods_3/00-16.jpg',
				food_intro:'味道鲜美，营养丰富'
 			},
 			{
				food_id:'03-017',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'鸡蛋肉丸粥',
				food_old_price:'¥300',
				food_price:'¥38',
				food_sales:'234单',
				food_pic:'images/foods/foods_3/00-17.jpg',
				food_intro:'蛋白质丰富，营养健康'
 			},
 			{
				food_id:'03-018',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'银耳粥',
				food_old_price:'¥300',
				food_price:'¥22',
				food_sales:'234单',
				food_pic:'images/foods/foods_3/00-18.jpg',
				food_intro:'夏季的解暑小能手'
 			},
 			{
				food_id:'03-019',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'红豆莲子粥',
				food_old_price:'¥300',
				food_price:'¥23',
				food_sales:'234单',
				food_pic:'images/foods/foods_3/00-19.jpg',
				food_intro:'补血益气，绝对的营养健康'
 			},
 			{
				food_id:'03-020',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'枸杞粥',
				food_old_price:'¥300',
				food_price:'¥30',
				food_sales:'21单',
				food_pic:'images/foods/foods_3/00-20.jpg',
				food_intro:'有益于女性的粥，好处又健康'
 			},
 			{
				food_id:'03-021',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'香菇粥',
				food_old_price:'¥300',
				food_price:'¥16',
				food_sales:'123单',
				food_pic:'images/foods/foods_3/00-21.jpg',
				food_intro:'香气逼人，营养美味'
 			},
 			{
				food_id:'03-022',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'红豆莲藕粥',
				food_old_price:'¥300',
				food_price:'¥24',
				food_sales:'232单',
				food_pic:'images/foods/foods_3/00-22.jpg',
				food_intro:'滋补益气，美容养颜'
 			},
 			{
				food_id:'03-023',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'青菜南瓜粥',
				food_old_price:'¥300',
				food_price:'¥14',
				food_sales:'232单',
				food_pic:'images/foods/foods_3/00-23.jpg',
				food_intro:'物美价廉，还好吃'
 			},
 			{
				food_id:'03-024',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'红豆地瓜粥',
				food_old_price:'¥300',
				food_price:'¥16',
				food_sales:'231单',
				food_pic:'images/foods/foods_3/00-24.jpg',
				food_intro:'营养助消化'
 			},
 			{
				food_id:'03-025',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'红枣玉米粥',
				food_old_price:'¥300',
				food_price:'¥28',
				food_sales:'234单',
				food_pic:'images/foods/foods_3/00-25.jpg',
				food_intro:'补血益气，补充能量'
 			},
 			{
				food_id:'03-026',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'青菜香菇粥',
				food_old_price:'¥300',
				food_price:'¥18',
				food_sales:'234单',
				food_pic:'images/foods/foods_3/00-26.jpg',
				food_intro:'健康营养，助消化'
 			},
 			{
				food_id:'03-027',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'八宝粥',
				food_old_price:'¥300',
				food_price:'¥16',
				food_sales:'65单',
				food_pic:'images/foods/foods_3/00-27.jpg',
				food_intro:'万能的充饥宝'
 			},
 			{
				food_id:'03-028',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'花生鸡末粥',
				food_old_price:'¥300',
				food_price:'¥35',
				food_sales:'235单',
				food_pic:'images/foods/foods_3/00-28.jpg',
				food_intro:'营养健康，滋补健康'
 			},
 			{
				food_id:'03-029',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'虾仁砂锅粥',
				food_old_price:'¥300',
				food_price:'¥36',
				food_sales:'32单',
				food_pic:'images/foods/foods_3/00-29.jpg',
				food_intro:'美味虾仁，清鲜可口'
 			},
 			{
				food_id:'03-030',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'蟹粥',
				food_old_price:'¥300',
				food_price:'¥34',
				food_sales:'23单',
				food_pic:'images/foods/foods_3/00-30.jpg',
				food_intro:'美味蟹仁，清鲜可口'
 			},
 			{
				food_id:'03-031',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'番茄心粥',
				food_old_price:'¥300',
				food_price:'¥22',
				food_sales:'124单',
				food_pic:'images/foods/foods_3/00-31.jpg',
				food_intro:'美味的番茄，清甜的香粥'
 			},
 			{
				food_id:'03-032',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'大虾粥',
				food_old_price:'¥300',
				food_price:'¥38',
				food_sales:'234单',
				food_pic:'images/foods/foods_3/00-32.jpg',
				food_intro:'虾味十足虾味十足'
 			},
 			{
				food_id:'03-033',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'青菜肉丸粥',
				food_old_price:'¥300',
				food_price:'¥23',
				food_sales:'234单',
				food_pic:'images/foods/foods_3/00-33.jpg',
				food_intro:'荤素搭配，营养健康'
 			},
 			{
				food_id:'03-034',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'鸡蛋肉片粥',
				food_old_price:'¥300',
				food_price:'¥28',
				food_sales:'453单',
				food_pic:'images/foods/foods_3/00-34.jpg',
				food_intro:'蛋白质丰富，能量丰富'
 			},
 			{
				food_id:'03-035',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'豆角腊肉粥',
				food_old_price:'¥300',
				food_price:'¥25',
				food_sales:'63单',
				food_pic:'images/foods/foods_3/00-35.jpg',
				food_intro:'新鲜的豆角，飘香的腊肉'
 			},
 			{
				food_id:'03-036',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'黄鳝粥',
				food_old_price:'¥300',
				food_price:'¥43',
				food_sales:'124单',
				food_pic:'images/foods/foods_3/00-36.jpg',
				food_intro:'滋补益气，好吃好吃'
 			},
 			{
				food_id:'03-037',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'绿豆粥',
				food_old_price:'¥300',
				food_price:'¥16',
				food_sales:'345单',
				food_pic:'images/foods/foods_3/00-37.jpg',
				food_intro:'夏季的解暑小能手'
 			},
 			{
				food_id:'03-038',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'百合薏仁粥',
				food_old_price:'¥300',
				food_price:'¥32',
				food_sales:'523单',
				food_pic:'images/foods/foods_3/00-38.jpg',
				food_intro:'清香可口，舌有余香'
 			},
 			{
				food_id:'03-039',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'紫薯粥',
				food_old_price:'¥300',
				food_price:'¥14',
				food_sales:'231单',
				food_pic:'images/foods/foods_3/00-39.jpg',
				food_intro:'超级浓香的紫薯粥'
 			},
 			{
				food_id:'03-040',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'肉丝粥',
				food_old_price:'¥300',
				food_price:'¥16',
				food_sales:'83单',
				food_pic:'images/foods/foods_3/00-40.jpg',
				food_intro:'好喝的粥超级好喝'
 			},
 			{
				food_id:'03-041',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'枸杞银耳粥',
				food_old_price:'¥300',
				food_price:'¥24',
				food_sales:'232单',
				food_pic:'images/foods/foods_3/00-41.jpg',
				food_intro:'超级营养的粥，你值得喝'
 			},
 			{
				food_id:'03-042',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'虾蛤粥',
				food_old_price:'¥300',
				food_price:'¥45',
				food_sales:'24单',
				food_pic:'images/foods/foods_3/00-42.jpg',
				food_intro:'超级营养，滋补益气'
 			},
 			{
				food_id:'03-043',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'海鲜粥',
				food_old_price:'¥300',
				food_price:'¥45',
				food_sales:'324单',
				food_pic:'images/foods/foods_3/00-43.jpg',
				food_intro:'鲜香美味，好喝，真的好喝'
 			},
 			{
				food_id:'03-044',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'肉葱粥',
				food_old_price:'¥300',
				food_price:'¥',
				food_sales:'单',
				food_pic:'images/foods/foods_3/00-44.jpg',
				food_intro:''
 			},
 			{
				food_id:'03-045',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'五谷藕片粥',
				food_old_price:'¥300',
				food_price:'¥35',
				food_sales:'432单',
				food_pic:'images/foods/foods_3/00-45.jpg',
				food_intro:'营养美味，健康可口'
 			},
 			{
				food_id:'03-046',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'咸肉粥',
				food_old_price:'¥300',
				food_price:'¥26',
				food_sales:'23单',
				food_pic:'images/foods/foods_3/00-46.jpg',
				food_intro:'味道十足，重口味者的最爱'
 			},
 			{
				food_id:'03-047',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'猪肝粥',
				food_old_price:'¥300',
				food_price:'¥16',
				food_sales:'342单',
				food_pic:'images/foods/foods_3/00-47.jpg',
				food_intro:'滋补益气，健康营养'
 			},
 			{
				food_id:'03-048',
				seller_id:'03',
				seller_name:'粥末',
				food_name:'五谷莲子粥',
				food_old_price:'¥300',
				food_price:'¥35',
				food_sales:'325单',
				food_pic:'images/foods/foods_3/00-48.jpg',
				food_intro:'健康美味，营养好喝'
 			}
		]
	},
	{
		seller_id:'04',
		seller_pic:'images/seller/seller_4.png',  //商家头像
		seller_name:'真湘菜馆', //商家名称
		seller_intro:'正宗湘菜，百年招牌，物美价廉', //商家简介
		seller_acti:'全场满199减20，还免费送汤', //商家活动（全场几折）
		seller_notice:'如果你是辣的爱好者，就请你来到真湘菜馆',      //商家公告
		start_price:'￥35', //起步价
		delivery_fee:'￥3',  //配送费
		delivery_time:'45分钟即达', //配送时间（周几到周几，几点到几点）
		seller_sales:'月售156单', //月销售量
		seller_tel:'13459001235',
		seller_address:'深圳市天利名城购物中心', //商家地址
		seller_foods:[  //菜品
			{
				food_id:'04-001',
				seller_id:'04',
				seller_name:'真湘菜馆', //商家名称
				food_name:'如鱼得水', //名字
				food_old_price:'¥400',
				food_price:'￥116', //价格
				food_sales:'54单',  //月销售量
				food_pic:'images/foods/foods_4/00-01.jpg',   //菜图
				food_intro:'新鲜的鱼清蒸成美味，鲜美的汁儿香味倍增，丝滑爽口'  //菜简介
 			},    
			{
				food_id:'04-002',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'红烧全鸡',
				food_old_price:'¥400',
				food_price:'￥88',
				food_sales:'123单', 
				food_pic:'images/foods/foods_4/00-02.jpg',
				food_intro:'全鸡切片，完全入味，辣味十足，肥美好吃'
			},
			{
				food_id:'04-003',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'爆炒肉块',
				food_old_price:'¥400',
				food_price:'￥68',
				food_sales:'143单', 
				food_pic:'images/foods/foods_4/00-03.jpg',
				food_intro:'瘦肉者请往这里看，辣炒猪瘦肉，香辣可口味道绝'
			},
			{
				food_id:'04-004',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'香辣豆腐',
				food_old_price:'¥400',
				food_price:'￥45',
				food_sales:'156单', 
				food_pic:'images/foods/foods_4/00-04.jpg',
				food_intro:'香香辣辣的香辣豆腐，香味十足，辣味十足，好吃又便宜'
			},
			{
				food_id:'04-005',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'麻辣香锅',
				food_old_price:'¥400',
				food_price:'￥45',
				food_sales:'242单', 
				food_pic:'images/foods/foods_4/00-05.jpg',
				food_intro:'纯正香辣，美味可口'
			},
			{
				food_id:'04-006',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'水煮扣肉',
				food_old_price:'¥400',
				food_price:'￥78',
				food_sales:'65单', 
				food_pic:'images/foods/foods_4/00-06.jpg',
				food_intro:'秘制鲜汤，扣肉入口即化'
			},
			{
				food_id:'04-007',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'红烧猪蹄',
				food_old_price:'¥400',
				food_price:'￥88',
				food_sales:'98单', 
				food_pic:'images/foods/foods_4/00-08.jpg',
				food_intro:'猪蹄中含有丰富的胶原蛋白，而且有很好吃，美容又养颜，女性朋友们的闺蜜'
			},
			{
				food_id:'04-008',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'玉米排骨汤',
				food_old_price:'¥400',
				food_price:'￥78',
				food_sales:'76单', 
				food_pic:'images/foods/foods_4/00-07.jpg',
				food_intro:'玉米排骨，鲜美营养'
			},
			{
				food_id:'04-009',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'梅菜五花肉',
				food_old_price:'¥400',
				food_price:'￥67',
				food_sales:'23单', 
				food_pic:'images/foods/foods_4/00-07.jpg',
				food_intro:'自家做的梅菜，干净营养，五花肉也是美味，他们在一起更配哦'
			},
			{
				food_id:'04-010',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'冰花甲',
				food_old_price:'￥96',
				food_price:'￥87',
				food_sales:'43单', 
				food_pic:'images/foods/foods_4/00-10.jpg',
				food_intro:'正宗海鲜，绝对的美味'
			},
			{
				food_id:'04-011',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'西兰花肉丁',
				food_old_price:'¥400',
				food_price:'¥98',
				food_sales:'267单',
				food_pic:'images/foods/foods_4/00-11.jpg',
				food_intro:'蔬菜和肉，均衡营养'
 			}, 
 			{
				food_id:'04-012',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'茶树菇焖鸡',
				food_old_price:'¥400',
				food_price:'¥108',
				food_sales:'94单',
				food_pic:'images/foods/foods_4/00-12.jpg',
				food_intro:'茶树菇焖的鸡，味美汤营养'
 			}, 
 			{
				food_id:'04-013',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'土豆焖肉丁',
				food_old_price:'¥400',
				food_price:'¥89',
				food_sales:'157单',
				food_pic:'images/foods/foods_4/00-13.jpg',
				food_intro:'好吃可口的家常菜'
 			}, 
 			{
				food_id:'04-014',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'海鲜大餐',
				food_old_price:'¥400',
				food_price:'¥178',
				food_sales:'256单',
				food_pic:'images/foods/foods_4/00-14.jpg',
				food_intro:'超级好吃的海鲜汇'
 			}, 
 			{
				food_id:'04-015',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'闻鸡起舞',
				food_old_price:'¥400',
				food_price:'¥145',
				food_sales:'93单',
				food_pic:'images/foods/foods_4/00-15.jpg',
				food_intro:'色香味俱全阿吉吗都喜欢吃的鸡'
 			}, 
 			{
				food_id:'04-016',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'叫花鸡',
				food_old_price:'¥400',
				food_price:'¥156',
				food_sales:'234单',
				food_pic:'images/foods/foods_4/00-16.jpg',
				food_intro:'超级好吃传统方法做成的烤鸡'
 			}, 
 			{
				food_id:'04-017',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'爆炒虾仁',
				food_old_price:'¥400',
				food_price:'¥98',
				food_sales:'145单',
				food_pic:'images/foods/foods_4/00-17.jpg',
				food_intro:'美味中的美味，海鲜者的喜爱'
 			}, 
 			{
				food_id:'04-018',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'果蹄',
				food_old_price:'¥400',
				food_price:'¥98',
				food_sales:'453单',
				food_pic:'images/foods/foods_4/00-18.jpg',
				food_intro:'不但好吃，还含有丰富的胶原蛋白'
 			}, 
 			{
				food_id:'04-019',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'麻辣鱼',
				food_old_price:'¥400',
				food_price:'¥88',
				food_sales:'324单',
				food_pic:'images/foods/foods_4/00-19.jpg',
				food_intro:'好好吃的麻辣鱼'
 			}, 
 			{
				food_id:'04-020',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'玉米排骨汤',
				food_old_price:'¥400',
				food_price:'¥48',
				food_sales:'234单',
				food_pic:'images/foods/foods_4/00-20.jpg',
				food_intro:'营养丰富，汤的最佳选择'
 			}, 
 			{
				food_id:'04-021',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'剁椒鱼头',
				food_old_price:'¥400',
				food_price:'¥87',
				food_sales:'544单',
				food_pic:'images/foods/foods_4/00-21.jpg',
				food_intro:'辣辣辣，绝对美味'
 			}, 
 			{
				food_id:'04-022',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'肉排拱桥',
				food_old_price:'¥400',
				food_price:'¥108',
				food_sales:'343单',
				food_pic:'images/foods/foods_4/00-22.jpg',
				food_intro:'设计独特，营养丰富，好吃，辣味十足'
 			}, 
 			{
				food_id:'04-023',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'汤圆',
				food_old_price:'¥400',
				food_price:'¥18',
				food_sales:'332单',
				food_pic:'images/foods/foods_4/00-23.jpg',
				food_intro:'营养丰富的早晚餐'
 			}, 
 			{
				food_id:'04-024',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'红烧肉片',
				food_old_price:'¥400',
				food_price:'¥58',
				food_sales:'456单',
				food_pic:'images/foods/foods_4/00-24.jpg',
				food_intro:'绝对的瘦肉，不惨任何肥肉，吃起来超级有味道'
 			}, 
 			{
				food_id:'04-025',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'水煮鸭',
				food_old_price:'¥400',
				food_price:'¥78',
				food_sales:'145单',
				food_pic:'images/foods/foods_4/00-25.jpg',
				food_intro:'很营养的鸭汤，鸭也很爽口'
 			}, 
 			{
				food_id:'04-026',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'土豆烧肉',
				food_old_price:'¥400',
				food_price:'¥35',
				food_sales:'534单',
				food_pic:'images/foods/foods_4/00-26.jpg',
				food_intro:'人人都消费得起的好吃的家常菜'
 			}, 
 			{
				food_id:'04-027',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'天女散花',
				food_old_price:'¥400',
				food_price:'¥128',
				food_sales:'154单',
				food_pic:'images/foods/foods_4/00-27.jpg',
				food_intro:'看起来好看，吃起来简直美味'
 			}, 
 			{
				food_id:'04-028',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'披萨',
				food_old_price:'¥400',
				food_price:'¥57',
				food_sales:'456单',
				food_pic:'images/foods/foods_4/00-28.jpg',
				food_intro:'好吃有嚼劲'
 			}, 
 			{
				food_id:'04-029',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'炒肉片',
				food_old_price:'¥400',
				food_price:'¥35',
				food_sales:'353单',
				food_pic:'images/foods/foods_4/00-29.jpg',
				food_intro:'唇齿留香，色味俱佳'
 			}, 
 			{
				food_id:'04-030',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'鸳鸯锅',
				food_old_price:'¥400',
				food_price:'¥98',
				food_sales:'321单',
				food_pic:'images/foods/foods_4/00-30.jpg',
				food_intro:'口舌生香大快朵颐'
 			}, 
 			{
				food_id:'04-031',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'人间方圆',
				food_old_price:'¥400',
				food_price:'¥78',
				food_sales:'34单',
				food_pic:'images/foods/foods_4/00-31.jpg',
				food_intro:'外观温馨，看起来有食欲，吃着更有味'
 			}, 
 			{
				food_id:'04-032',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'猪蹄面',
				food_old_price:'¥400',
				food_price:'¥28',
				food_sales:'532单',
				food_pic:'images/foods/foods_4/00-32.jpg',
				food_intro:'营养丰富，美容养颜'
 			}, 
 			{
				food_id:'04-033',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'干锅鱿鱼丝',
				food_old_price:'¥400',
				food_price:'¥56',
				food_sales:'643单',
				food_pic:'images/foods/foods_4/00-33.jpg',
				food_intro:'鱿鱼，营养丰富，好吃好吃'
 			}, {
				food_id:'04-034',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'干锅小黄鱼',
				food_old_price:'¥400',
				food_price:'¥77',
				food_sales:'456单',
				food_pic:'images/foods/foods_4/00-34.jpg',
				food_intro:'真正好吃的小黄鱼，可口美味'
 			}, 
 			{
				food_id:'04-035',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'砂锅脆笋',
				food_old_price:'¥400',
				food_price:'¥45',
				food_sales:'353单',
				food_pic:'images/foods/foods_4/00-35.jpg',
				food_intro:'唇齿留香，色味俱佳'
 			}, 
 			{
				food_id:'04-036',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'辣炒酱干',
				food_old_price:'¥400',
				food_price:'¥28',
				food_sales:'321单',
				food_pic:'images/foods/foods_4/00-36.jpg',
				food_intro:'好吃可口的家常菜'
 			}, 
 			{
				food_id:'04-037',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'爆炒牛肚',
				food_old_price:'¥400',
				food_price:'¥88',
				food_sales:'34单',
				food_pic:'images/foods/foods_4/00-37.jpg',
				food_intro:'好吃有嚼劲，真正的美味'
 			}, 
 			{
				food_id:'04-038',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'芹菜烧茄子',
				food_old_price:'¥400',
				food_price:'¥28',
				food_sales:'538单',
				food_pic:'images/foods/foods_4/00-38.jpg',
				food_intro:'色香味俱全，很好下饭的一道菜'
 			}, 
 			{
				food_id:'04-039',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'糖醋里脊',
				food_old_price:'¥400',
				food_price:'¥46',
				food_sales:'143单',
				food_pic:'images/foods/foods_4/00-39.jpg',
				food_intro:'酸酸甜甜好好吃哦'
 			},
 			{
				food_id:'04-040',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'蒜苗炒虾',
				food_old_price:'¥400',
				food_price:'¥87',
				food_sales:'456单',
				food_pic:'images/foods/foods_4/00-40.jpg',
				food_intro:'蒜苗的清香，虾的肥美，想到就会咽口水'
 			}, 
 			{
				food_id:'04-041',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'凉拌黄瓜',
				food_old_price:'¥400',
				food_price:'¥25',
				food_sales:'353单',
				food_pic:'images/foods/foods_4/00-41.jpg',
				food_intro:'餐前凉菜，开胃'
 			}, 
 			{
				food_id:'04-042',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'辣炒藕片',
				food_old_price:'¥400',
				food_price:'¥38',
				food_sales:'121单',
				food_pic:'images/foods/foods_4/00-42.jpg',
				food_intro:'口舌生香大快朵颐'
 			}, 
 			{
				food_id:'04-043',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'清炒蚕豆',
				food_old_price:'¥400',
				food_price:'¥78',
				food_sales:'34单',
				food_pic:'images/foods/foods_4/00-43.jpg',
				food_intro:'带你走进乡村的世界，好吃哦'
 			}, 
 			{
				food_id:'04-044',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'清炒扁豆',
				food_old_price:'¥400',
				food_price:'¥26',
				food_sales:'243单',
				food_pic:'images/foods/foods_4/00-44.jpg',
				food_intro:'营养丰富，绝对绿色食品'
 			},
 			{
				food_id:'04-045',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'手撕包菜',
				food_old_price:'¥400',
				food_price:'¥18',
				food_sales:'235单',
				food_pic:'images/foods/foods_4/00-45.jpg',
				food_intro:'平凡中的美味，美味'
 			}, 
 			{
				food_id:'04-046',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'香辣鸡杂',
				food_old_price:'¥400',
				food_price:'¥58',
				food_sales:'347单',
				food_pic:'images/foods/foods_4/00-46.jpg',
				food_intro:'好吃哦，真的好吃'
 			}, 
 			{
				food_id:'04-047',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'千页豆腐',
				food_old_price:'¥400',
				food_price:'¥46',
				food_sales:'123单',
				food_pic:'images/foods/foods_4/00-47.jpg',
				food_intro:'不一样的豆腐，不一样的味道'
 			},
 			{
				food_id:'04-048',
				seller_id:'04',
				seller_name:'真湘菜馆',
				food_name:'青椒焖土鸡',
				food_old_price:'¥400',
				food_price:'¥56',
				food_sales:'643单',
				food_pic:'images/foods/foods_4/00-48.jpg',
				food_intro:'正宗土鸡，营养健康'
 			}
		]
	},
	{
		seller_id:'05',
		seller_pic:'images/seller/seller_5.png',  //商家头像
		seller_name:'思维特', //商家名称
		seller_intro:'如果您心情不好，或者低落，就请您来到我们思维·特甜品屋，五门给您带来甜蜜的感觉，好味道好心情，尽在思维·特', //商家简介
		seller_acti:'七夕全场情侣套餐8折起', //商家活动（全场几折）
		seller_notice:'七夕了怎么办，带着女朋友来思维·特，有优惠有折扣',      //商家公告
		start_price:'￥25', //起步价
		delivery_fee:'￥5',  //配送费
		delivery_time:'20分钟即达', //配送时间（周几到周几，几点到几点）
		seller_sales:'月售534单', //月销售量
		seller_tel:'18701235576',  //商家联系方式
		seller_address:'深圳市太阳百货', //商家地址
		seller_foods:[  //菜品
			{
				food_id:'05-001',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'梦幻冰淇淋奶球',
				food_price:'￥36',
				food_sales:'57单',
				food_pic:'images/foods/foods_5/00-01.jpg',
				food_intro:'梦幻的水果，甜甜的奶油冰淇淋，入口即化，丝滑爽口'
 			},    
			{
				food_id:'05-002',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'华夫果品',
				food_price:'￥85',
				food_sales:'145单',
				food_pic:'images/foods/foods_5/00-02.jpg',
				food_intro:'奶香飘千里的华夫饼，新鲜的火龙果，纯纯的水果奶球，只为等您的到来'
			},
			{
				food_id:'05-003',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'浪漫满屋',
				food_price:'￥48.5',
				food_sales:'134单',
				food_pic:'images/foods/foods_5/00-03.jpg',
				food_intro:'特价特价，仅售48.5元，最高价值99元双人套餐！布置温馨，幽雅小资氛围！口感细腻独特，甜甜蜜蜜入心，感受闲暇时光，随心演奏悠然序曲！节假日通用！'
			},
			{
				food_id:'05-004',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'兰瑟',
				food_price:'￥30',
				food_sales:'77单',
				food_pic:'images/foods/foods_5/00-04.jpg',
				food_intro:'软蛋糕，梦幻般的蓝色，绝对的软蛋糕，好吃好吃大写的好吃'
			},
			{
				food_id:'05-005',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'千层奶盖',
				food_price:'￥56',
				food_sales:'132单',
				food_pic:'images/foods/foods_5/00-05.jpg',
				food_intro:'每一层，都是不一样的味道，给您带来不一样的甜美心情'
			},
			{
				food_id:'05-006',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'黑色森林',
				food_price:'￥35',
				food_sales:'157单',
				food_pic:'images/foods/foods_5/00-06.jpg',
				food_intro:'鲜香浓密葡萄汁加上榛子，味道丝滑爽口'
			},
			{
				food_id:'05-007',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'果香蛋糕',
				food_price:'￥35',
				food_sales:'66单',
				food_pic:'images/foods/foods_5/00-07.jpg',
				food_intro:'软软的蛋糕，夹着各种水果布丁，色彩的搭配，有颜又有味'
			},
			{
				food_id:'05-008',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'珍珠花簇',
				food_price:'￥25',
				food_sales:'86单',
				food_pic:'images/foods/foods_5/00-08.jpg',
				food_intro:'一丛丛奶油花簇，嵌着珍珠般的糖果，好吃的不得了'
			},
			{
				food_id:'05-009',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'千层蛋糕',
				food_price:'￥28',
				food_sales:'324单',
				food_pic:'images/foods/foods_5/00-09.jpg',
				food_intro:'美味的千层蛋糕，还有青提的芬香'
			},
			{
				food_id:'05-010',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'披萨',
				food_price:'￥68',
				food_sales:'133单',
				food_pic:'images/foods/foods_5/00-10.jpg',
				food_intro:'好吃有嚼劲'
			},
			{
				food_id:'05-011',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'苏打水',
				food_price:'￥28',
				food_sales:'231单',
				food_pic:'images/foods/foods_5/00-11.jpg',
				food_intro:'健康营养，补充能量'
			},
			{
				food_id:'05-012',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'草莓奶酥',
				food_price:'￥45',
				food_sales:'234单',
				food_pic:'images/foods/foods_5/00-12.jpg',
				food_intro:'味道清甜，好吃好喝'
			},
			{
				food_id:'05-013',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'蜜橙',
				food_price:'￥15',
				food_sales:'322单',
				food_pic:'images/foods/foods_5/00-13.jpg',
				food_intro:'清甜香橙，美味可口'
			},
			{
				food_id:'05-014',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'甜品饮品套餐',
				food_price:'￥135',
				food_sales:'524单',
				food_pic:'images/foods/foods_5/00-14.jpg',
				food_intro:'超值套餐，多人共享'
			},
			{
				food_id:'05-015',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'青海',
				food_price:'￥15',
				food_sales:'345单',
				food_pic:'images/foods/foods_5/00-15.jpg',
				food_intro:'清甜解渴，味道绝爽'
			},
			{
				food_id:'05-016',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'芒果刨冰',
				food_price:'￥35',
				food_sales:'86单',
				food_pic:'images/foods/foods_5/00-16.jpg',
				food_intro:'好吃美味，冰爽解渴'
			},
			{
				food_id:'05-017',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'温馨早餐',
				food_price:'￥38',
				food_sales:'324单',
				food_pic:'images/foods/foods_5/00-17.jpg',
				food_intro:'超值早餐，咖啡蛋糕只要38'
			},
			{
				food_id:'05-018',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'水果屋',
				food_price:'￥35',
				food_sales:'53单',
				food_pic:'images/foods/foods_5/00-18.jpg',
				food_intro:'三种水果堆积而成，好吃哦'
			},
			{
				food_id:'05-019',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'神秘',
				food_price:'￥45',
				food_sales:'323单',
				food_pic:'images/foods/foods_5/00-19.jpg',
				food_intro:'神秘浪漫，带有巧克力的苦涩'
			},
			{
				food_id:'05-020',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'温馨小屋',
				food_price:'￥36',
				food_sales:'324单',
				food_pic:'images/foods/foods_5/00-20.jpg',
				food_intro:'甜蜜带有温馨感，让你吃出好心情'
			},
			{
				food_id:'05-021',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'青柠牛奶',
				food_price:'￥24',
				food_sales:'754单',
				food_pic:'images/foods/foods_5/00-21.jpg',
				food_intro:'青柠配牛奶，奶香青柠'
			},
			{
				food_id:'05-022',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'马卡龙',
				food_price:'￥76',
				food_sales:'323单',
				food_pic:'images/foods/foods_5/00-22.jpg',
				food_intro:'好吃好吃真的好吃'
			},
			{
				food_id:'05-023',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'蛋糕奶球',
				food_price:'￥78',
				food_sales:'533单',
				food_pic:'images/foods/foods_5/00-23.jpg',
				food_intro:'鲜香奶酪，入口即化'
			},
			{
				food_id:'05-024',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'拿铁',
				food_price:'￥72',
				food_sales:'545单',
				food_pic:'images/foods/foods_5/00-24.jpg',
				food_intro:'热腾腾的拿铁，给你带去温暖'
			},
			{
				food_id:'05-025',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'果蔬汁',
				food_price:'￥18',
				food_sales:'424单',
				food_pic:'images/foods/foods_5/00-25.jpg',
				food_intro:'营养健康，好喝美味'
			},
			{
				food_id:'05-026',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'蛋糕酥',
				food_price:'￥40',
				food_sales:'436单',
				food_pic:'images/foods/foods_5/00-26.jpg',
				food_intro:'香甜可口，美味一绝'
			},
			{
				food_id:'05-027',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'蛋糕派',
				food_price:'￥38',
				food_sales:'234单',
				food_pic:'images/foods/foods_5/00-27.jpg',
				food_intro:'很好吃，长得很好看'
			},
			{
				food_id:'05-028',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'甜甜圈',
				food_price:'￥27',
				food_sales:'456单',
				food_pic:'images/foods/foods_5/00-28.jpg',
				food_intro:'超级甜超级好吃超级美味'
			},
			{
				food_id:'05-029',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'葡萄刨冰',
				food_price:'￥16',
				food_sales:'324单',
				food_pic:'images/foods/foods_5/00-29.jpg',
				food_intro:'清香好吃，美味可口'
			},
			{
				food_id:'05-030',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'奇异草莓',
				food_price:'￥35',
				food_sales:'234单',
				food_pic:'images/foods/foods_5/00-30.jpg',
				food_intro:'各式各样的"草莓"蛋糕'
			},
			{
				food_id:'05-031',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'亲密巧克力',
				food_price:'￥45',
				food_sales:'234单',
				food_pic:'images/foods/foods_5/00-31.jpg',
				food_intro:'好吃好吃超好吃'
			},
			{
				food_id:'05-032',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'泡芙',
				food_price:'￥35',
				food_sales:'435单',
				food_pic:'images/foods/foods_5/00-32.jpg',
				food_intro:'超级好吃的泡芙，奶香浓郁'
			},
			{
				food_id:'05-033',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'奇异果巧克力奶茶',
				food_price:'￥15',
				food_sales:'324单',
				food_pic:'images/foods/foods_5/00-33.jpg',
				food_intro:'巧克力味十足，超级正宗'
			},
			{
				food_id:'05-034',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'温馨小屋',
				food_price:'￥65',
				food_sales:'234单',
				food_pic:'images/foods/foods_5/00-34.jpg',
				food_intro:'好酥好好吃的巧克力奶油'
			},
			{
				food_id:'05-035',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'我的皇后',
				food_price:'￥68',
				food_sales:'64单',
				food_pic:'images/foods/foods_5/00-35.jpg',
				food_intro:'好吃超好吃，甜蜜温馨'
			},
			{
				food_id:'05-036',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'华夫果品',
				food_price:'￥45',
				food_sales:'765单',
				food_pic:'images/foods/foods_5/00-36.jpg',
				food_intro:'营养健康，美味早餐'
			},
			{
				food_id:'05-037',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'果蔬汉堡',
				food_price:'￥25',
				food_sales:'856单',
				food_pic:'images/foods/foods_5/00-37.jpg',
				food_intro:'聚划算，超好吃'
			},
			{
				food_id:'05-038',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'鲜奶巧克力',
				food_price:'￥42',
				food_sales:'534单',
				food_pic:'images/foods/foods_5/00-38.jpg',
				food_intro:'超级好吃，入口即化'
			},
			{
				food_id:'05-039',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'分层奶茶',
				food_price:'￥18',
				food_sales:'854单',
				food_pic:'images/foods/foods_5/00-39.jpg',
				food_intro:'人人都在喝的水果牛奶茶'
			},
			{
				food_id:'05-040',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'奇异果蛋糕',
				food_price:'￥28',
				food_sales:'853单',
				food_pic:'images/foods/foods_5/00-40.jpg',
				food_intro:'酥软美味，你的最爱'
			},
			{
				food_id:'05-041',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'浓密森林',
				food_price:'￥38',
				food_sales:'756单',
				food_pic:'images/foods/foods_5/00-41.jpg',
				food_intro:'神秘感十足，真的很好吃'
			},
			{
				food_id:'05-042',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'巧克力桃酥',
				food_price:'￥26',
				food_sales:'546单',
				food_pic:'images/foods/foods_5/00-42.jpg',
				food_intro:'很脆很脆的巧克力味桃酥饼'
			},
			{
				food_id:'05-043',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'仙奶球',
				food_price:'￥25',
				food_sales:'533单',
				food_pic:'images/foods/foods_5/00-43.jpg',
				food_intro:'奶香十足，入口即化'
			},
			{
				food_id:'05-044',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'泡泡蔟',
				food_price:'￥32',
				food_sales:'543单',
				food_pic:'images/foods/foods_5/00-44.jpg',
				food_intro:'好好吃的奶油蛋糕'
			},
			{
				food_id:'05-045',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'红豆香芋奶',
				food_price:'￥24',
				food_sales:'456单',
				food_pic:'images/foods/foods_5/00-45.jpg',
				food_intro:'红豆入口即化，香芋奶好好喝'
			},
			{
				food_id:'05-046',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'巧克力屋',
				food_price:'￥78',
				food_sales:'243单',
				food_pic:'images/foods/foods_5/00-46.jpg',
				food_intro:'巧克力味十足，超级正宗'
			},
			{
				food_id:'05-047',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'双球奶',
				food_price:'￥36',
				food_sales:'243单',
				food_pic:'images/foods/foods_5/00-47.jpg',
				food_intro:'奶香十足，入口即化'
			},
			{
				food_id:'05-048',
				seller_id:'05',
				seller_name:'思维·特',
				food_old_price:'¥500',
				food_name:'香草奶球',
				food_price:'￥48',
				food_sales:'342单',
				food_pic:'images/foods/foods_5/00-48.jpg',
				food_intro:'奶香十足，入口即化'
			},
		]
	}
]



// //购物车
// [
// 	{
// 		username:'',  //用户名
// 		food_pic:'',  //菜图 
// 		seller_name:'', //商家名
// 		food_name:'',  //名字
// 		food_old_price:'', //原价
// 		food_price:'', //价格
// 		number:'',    //个数
// 		tatal_price:''  //总价
// 	},
// 	{}
// ]
// //订单
// [
// 	{
// 		username:'',  //用户名
// 		food_pic:'',  //菜图
// 		seller_name:''  //商家名
// 		food_name:'',  //名字
// 		food_price:'', //价格
// 		number:'',    //个数
// 		tatal_price:''  //总价
// 	},
// 	{}
// ]

//用户信息
[
	{
		username:'',  //用户名
		password:'',  //密码
		sex:'',       //性别
		address:'',   //收货地址
		tel:'', //电话号码
		usertype:''   //类型:seller/client
	},
	{}
]

db.user.find():

[
	{username:'糖压瓶',sex:'female',password:'123456',address:'江西农业大学',tel:'12345678901',usertype:'client'},
	{username:'张三',sex:'male',password:'zhangsan',address:'深圳街777号',tel:'12345678901',usertype:'client'},
	{username:'爵士牛排',password:'jueshiniupai',seller_id:'01',usertype:'seller'},
	{username:'水煮江川',password:'shuizhujiangchuan',seller_id:'02', seller_id:'02',usertype:'seller'},
	{username:'粥末',password:'zhoumo',seller_id:'03',usertype:'seller'},
	{username:'真湘菜馆',password:'zhenxiangcaiguan',seller_id:'04',usertype:'seller'},
	{username:'思维特',password:'siweite',seller_id:'05',usertype:'seller'}
]
